# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-install

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]

      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.365
    hooks:
      - id: pyright

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.3.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        entry: ./scripts/run_eslint.sh
        additional_dependencies:
          - eslint@9.3.0
          - globals@15.3.0
          - "@eslint/js@9.3.0"
          - typescript-eslint@8.0.0-alpha.20

  - repo: local
    hooks:
      - id: eslint
        name: Run ESLint linter
        files: \.[jt]sx?$
        types: [file]
        language: node
        entry: ./scripts/run_eslint.sh
        additional_dependencies:
          - eslint@9.3.0
          - globals@15.3.0
          - "@eslint/js@9.3.0"
          - typescript-eslint@8.0.0-alpha.20


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier

ci:
  # Notes:
  # - We're skipping pyright because we don't have a genjax release with ArrayLike
  # TODO: we expect this condition to be temporary
  skip: [pyright]
