# Simple workflow for deploying static content to GitHub Pages
name: Render and Publish Docs

on:
  workflow_dispatch:
  push:
    branches:
      - sritchie/pages

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Create website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./dist

  publish:
    needs: build-deploy
    uses: probcomp/gen-website-private/.github/workflows/publish_private_website.yml@main
    with:
      artifact: website
